### PR TITLE
Add Election Header

### LINKED ISSUE #18: ElectionHeader
```
<ElectionHeader
   defaultValue=0 // the initially selected index, usually 0
   elections=[] // an array of election data objects
   onDone() // calls onDone(i) with the index of the object the user selected
>
```
link to figma: https://www.figma.com/file/IQKPx02pkBErpmhQoECoq9/Undebate?node-id=132%3A7175
image

### PR DESCRIPTION
**Pull request by rodolfonei**
Closes #18

### CODE REVIEW

**Comment by ddfridley** [comment]
@rodolfonei Bravo. Seems like you are getting to know react.  
Here are some next steps:

- [ ] Accept className and style as props and use them in the outer most div.  See # 8 in the recently updated [readme](https://github.com/EnCiv/undebate-ssp#notes-on-react-component-guidelines)
- [ ] Support onDone as in # 7 of the notes above - you will use the onChange event in the selector in order to generate the onDone event.  I don't think invalid is possible here, so always call it with `{valid: true, value: index}` Here is the code I mentioned before from the undebate project: 
```
        <select
          value={micIndex}
          onChange={event => {
            switchMic(event.target.value)
            setChangeMic(false)
          }}
        >
          {audioinputs.length > 0
            ? audioinputs.slice(1).map((input, index) => (
                <option value={index + 1} key={index + 1}>
                  {input.label}
                </option>
              ))
            : null}
        </select>
```
Value and key will need to be set in the option, so you can the the value out. But in this case value can be set to the index, no need to +1. 
- [ ] Support the defaultValue - you might just set defaultValue={defaultValue} in the selector. Or it might need to be value={defaultValue}
- [ ] Okay this isn't in the spec, but lets move <SvgHome> into a separate component app/components/home-button.js - for now. <HomeButton /> will return <SvgHome> just like you are rendering now.  But I'll make an issue for someone to add the home button functionality to it, and then when they do it will just work in the <ElectionHeader />.  If this doesn't make sense let me know and I will explain more.
- [ ] Create <BackButton> component using SvgChevronLeft as above.
- [ ] Create <InstructionButton> component using SvgBookOpen as above.

This issue was a little messy for your first react component - but it made me smile to see your progress. I hope you are feeling good about it too.

**Comment by rodolfonei** [comment]
Awesome, @ddfridley! It has been really exciting to work on this component, I am learning a lot. Thank you for your feedback, it will help very much to finish the issue, it resolves most of the doubts I was having until now. I will start to work on these new steps right away!

**Review by ddfridley — CHANGES_REQUESTED** [review]
@rodolfonei This is looking good!  We just need to put a little more in the story.  We need to display the result of the call to onDone.   Here is a good example of what to put in the story to do that: https://github.com/EnCiv/undebate-ssp/blob/main/stories/script_text_input.stories.js

**Comment by rodolfonei** [comment]
Done, @ddfridley! Please let me know if there is anything missing

**Review by ddfridley — APPROVED** [review]
Looks great! Thank you.

**Pull request merged**
