### PR TITLE
Upsert election doc#72

### LINKED ISSUE #72: upsert-election-doc
## Client Side
emit('upsert-election-doc', obj, ()=>{}}

## Server Side
socket-apis/upsert-election-doc.js
function upsertElectionDoc(obj, cb) {

obj can be a complete object, or more often, a subset of the complete obj that the user has just changed.

- [x] _id is required - if not present logger.error a massage and cb(undefined)
- [x] #98
- [x] check the object against the schema #46 - if it fails, cb(undefined) and logger.error a message.
- [x] upsert the object, after that succeed cb(true) if it fails cb(undefined) and logger.error a message.

see [create-topic](https://github.com/EnCiv/unpoll/blob/main/app/socket-apis/create-topic.js) in unpoll for a start.

### PR DESCRIPTION
**Pull request by kamui-fin**
Closes #72

### CODE REVIEW

**Review by ddfridley — CHANGES_REQUESTED** [review]
After you run localhost:3011/test-election-doc
you can do
```
mongo
> db.iotas.find({subject: "Election Document"}).pretty()     
```
The output is below.
Notice that the 1: { ...} got turned into "1": {...}.  It's a javascript thing. Object keys will always be strings and js will convert.

- [x] Please change the schema to require that these be strings. Is there a way to test for string of digits only? 
- [x] Please checkout https://www.npmjs.com/package/joi-objectid for validating the _id fields.
- [x] For uniqueId, and other objectID's as strings, is there a way to require length 24. Even better if we can limit the characters to whats valid (I think it's 0-9,a-f but not totally sure).

It's looking good though. This is a giant step toward getting a schema going. thanks.


```
{
        "_id" : {
                "timestamp" : 1643243504,
                "machine" : 13632437,
                "pid" : 29618,
                "increment" : 0
        },
        "candidates" : {
                "61e76bbefeaa4a25840d85d0" : {
                        "uniqueId" : "61e76bbefeaa4a25840d85d0",
                        "name" : "Sarah Jones",
                        "email" : "sarahjones@mail.com",
                        "office" : "President of the U.S.",
                        "region" : "United States",
                        "invitations" : [
                                {
                                        "_id" : {
                                                "timestamp" : 1643243504,
                                                "machine" : 13632437,
                                                "pid" : 29618,
                                                "increment" : 3
                                        },
                                        "text" : "text",
                                        "sentDate" : "date",
                                        "acceptedDate" : "date"
                                }
                        ],
                        "submissions" : [
                                {
                                        "_id" : {
                                                "timestamp" : 1643243504,
                                                "machine" : 13632437,
                                                "pid" : 29618,
                                                "increment" : 4
                                        },
                                        "url" : "url",
                                        "date" : "date"
                                }
                        ]
                },
                "61e76bfc8a82733d08f0cf12" : {
                        "uniqueId" : "61e76bfc8a82733d08f0cf12",
                        "name" : "Michael Jefferson",
                        "email" : "mikejeff@mail.com",
                        "office" : "President of the U.S.",
                        "region" : "United States",
                        "invitations" : [
                                {
                                        "_id" : {
                                                "timestamp" : 1643243504,
                                                "machine" : 13632437,
                                                "pid" : 29618,
                                                "increment" : 5
                                        },
                                        "text" : "Hi Mike, please send answers",
                                        "sentDate" : "date",
                                        "acceptedDate" : "date"
                                }
                        ],
                        "submissions" : [
                                {
                                        "_id" : {
                                                "timestamp" : 1643243504,
                                                "machine" : 13632437,
                                                "pid" : 29618,
                                                "increment" : 6
                                        },
                                        "url" : "date",
                                        "date" : "date"
                                }
                        ]
                }
        },
        "description" : "Election Document",
        "electionDate" : "2022-11-07T23:59:59.999Z",
        "electionName" : "U.S Presidential Election",
        "moderator" : {
                "name" : "Bill Smith",
                "email" : "billsmith@gmail.com",
                "message" : "Please be a moderator",
                "invitations" : [
                        {
                                "_id" : {
                                        "timestamp" : 1643243504,
                                        "machine" : 13632437,
                                        "pid" : 29618,
                                        "increment" : 1
                                },
                                "text" : "Hi Mike, please send answers",
                                "sentDate" : "date",
                                "acceptedDate" : "date"
                        }
                ],
                "submissions" : [
                        {
                                "_id" : {
                                        "timestamp" : 1643243504,
                                        "machine" : 13632437,
                                        "pid" : 29618,
                                        "increment" : 2
                                },
                                "url" : "url",
                                "date" : "date"
                        }
                ]
        },
        "organizationName" : "United States Federal Government",
        "questions" : {
                "0" : {
                        "text" : "What is your favorite color?",
                        "time" : "30"
                },
                "1" : {
                        "text" : "Do you have a pet?",
                        "time" : "60"
                },
                "2" : {
                        "text" : "Should we try to fix income inequality?",
                        "time" : "90"
                }
        },
        "script" : {
                "0" : {
                        "text" : "Welcome everyone. Our first question is: What is your favorite color?"
                },
                "1" : {
                        "text" : "Thank you. Our next Question is: Do you have a pet?"
                },
                "2" : {
                        "text" : "Great. And our last question is: Should we try to fix income inequality?"
                },
                "3" : {
                        "text" : "Thanks everyone for watching this!"
                }
        },
        "subject" : "Election Document",
        "timeline" : {
                "moderatorDeadlineReminderEmails" : {
                        "0" : {
                                "date" : "2022-01-07T22:09:32.952Z",
                                "sent" : true
                        },
                        "1" : {
                                "date" : "2022-01-07T22:09:32.952Z",
                                "sent" : false
                        }
                },
                "moderatorSubmissionDeadline" : {
                        "0" : {
                                "date" : "2022-01-07T22:09:32.952Z",
                                "sent" : true
                        }
                },
                "candidateDeadlineReminderEmails" : {
                        "0" : {
                                "date" : "2022-01-07T22:09:32.952Z",
                                "sent" : true
                        },
                        "1" : {
                                "date" : "2022-01-07T22:09:32.952Z",
                                "sent" : false
                        }
                },
                "candidateSubmissionDeadline" : {
                        "0" : {
                                "date" : "2022-01-07T22:09:32.952Z",
                                "sent" : true
                        }
                },
                "moderatorInviteDeadline" : {
                        "0" : {
                                "date" : "2022-01-07T22:09:32.952Z",
                                "sent" : true
                        },
                        "1" : {
                                "date" : "2022-01-07T22:09:32.952Z",
                                "sent" : false
                        }
                }
        },
        "undebateDate" : "date"
}
```

**Comment by ddfridley** [comment]
@kamui-fin I merged it with main because it wouldn't auto merge on github. You've done what was specified, but, I see there is a difference in the structure of the get-election-doc v. the upsert election don't where upsert doesn't have the webComponent part.  And really, all the data in upsert should be inside webComponent{ }.   But it's kind of fuzy and I want to talk it through tomorrow if your are going to be there.  Also, I'm questions why this is upsert - it doesn't create the doc if it doesnt exist.  Again - I want to talk it through. If you can't make it tomorrow - is there another time you could talk? Thx.

**Comment by kamui-fin** [comment]
No problem, we can discuss this through tomorrow.

**Review by ddfridley — APPROVED** [review]
@kamui-fin It may look like I changed a lot, but I changed the file name from upsert to find-and-set.  I also removed the _id from the electionDoc and clarified when _id is an object, vs. when id or uniqueId or parentId is a string. I also figured out I could add more specificity to the .string() tests like max and pattern. Please have a look and see if it make sense.  The objectId stuff is really tricky and I learned that isomorfic object-id module isn't right.  It's not creating a bson object - though it does create a string type ok.

**Pull request merged**
