### PR TITLE
Invitation#50

### LINKED ISSUE #50: Invitation component
```
<Invitation
    className={}
    style={}
    electionOM={[electionObj, electionMethods}
}
```
See #46 for electionOM details

- [x] `Submit Invite` should be a separate component, to which electionOM is passed.  For now create an app/submit-invite.js component that renders the button - and the rest will be done in another issue.
- [x] support message field seen in the figma

Prerequisites: 
- #9 

Figma: https://www.figma.com/file/yXrcMvg5EIwdLkHHxIdILh/Undebate-Self-Service-Portal?node-id=344%3A5652

- [x] See designer's comments to the right of the figma component drawing

image

### PR DESCRIPTION
**Pull request by kamui-fin**
Closes #50 

Also introduced an airbnb eslint & prettier setup to have a consistent code style with scripts to format and lint all code.

### CODE REVIEW

**Comment by ddfridley** [comment]
@kamui-fin we're going to have to break this down before we can merge it.
I pushed out changes to main a few days ago. You are going to need to pull those in and merge them.  But I'm worried that won't be easy because of all of the files that have changed due to prettier and lint.
So the fist task is to merge main into your branch. But it might be easier to take the updated main and create a new branch. Then pull the new files into that branch, and get it working. And then do a PR of that. And then do another PR that is the prettier and lint changes. 

Besides that  here are some other comments:
- [ ]  In this project we've been using .js even for the React components. It's looks a little wierd to have a few that are .jsx (and I know there are already a couple.  Do you see a reason not go use .js? 
- [ ] There are already a couple of files that use underscore as separators but I'd like to go to dash for consistency unless you see an issue.
- [ ] Create a story for when there is intialized data in electionObj
- [ ] In your stories pass electionOM={electionObj: {_id: '123abc', moderator: {name: "", email: ""}}, electionMethods: {upsert: obj=>{}}}
- [ ] svgSpeaker needs to be scaled. One way I can think of is to but it in a div and set the fortSize
- [ ] I'd like to reverse myself on how to submit the invitation.  Use: electionMethods.sendInvitation().  You don't have to pass anything, you just have to call it.  And pass it in in electionMethods above.  This way you'll be able to complete this component and test it without having to have other logic. Send one in from your story.
- [ ] the email address needs to be validates. ElectionTextInput takes a paramerter checkIsEmail

Thanks!

**Comment by kamui-fin** [comment]
I tried merging all the files from the origin's main but it looks like the `package.json` files are conflicting still for some reason.

**Comment by kamui-fin** [comment]
> It's looks a little wierd to have a few that are .jsx (and I know there are already a couple. Do you see a reason not go use .js?

Since this project's babel and webpack configuration already handles transpiling JSX in normal `.js` files, I don't think there's much of a technical reason to use `.jsx` over just `.js`. Mostly a convention/preference thing. I'll go ahead and rename the components to match up with the rest of the project.

> the email address needs to be validates. ElectionTextInput takes a paramerter checkIsEmail

I believe the component already handles this by passing `checkIsEmail`:
https://github.com/kamui-fin/undebate-ssp/blob/invitation%2350/app/components/invitation.jsx#L66

Thanks for all the feedback. I'll send a commit after implementing those suggestions.

**Comment by ddfridley** [comment]
@kamui-fin 
On prettier - with the people I was working with last year agreed on a prettier style - we agreed on single quotes rather than double quotes.  I'd like to stick with that.   Here is the .prettierc file from before.  I know we talked about it and agreed on tabWidth 4.  
```
{
  "trailingComma": "es5",
  "tabWidth": 2,
  "semi": false,
  "singleQuote": true,
  "jsxBracketSameLine": false,
  "arrowParens": "avoid",
  "printWidth": 120,
  "bracketSpacing": true,
  "jsxSingleQuote": false,
  "useTabs": false
}
```
I think rather than you and I deciding on the new standard, lets put it out for discussion.   Also, one thing I'd like to bring up is that I saw that this format:
```
const InstructionButton = () => {
    return <SvgBookOpen />;
};
```
Got changed to this:
```
const InstructionButton = function () {
    return <SvgBookOpen />
}
```
But I prefer the former style, as shorter and more modern, especially when the function declaration is being embedded in another function call. Is there a reason for this style?

I'm use to .prettierc rather than .prettierc.json is there a difference?  
Also I have the prettier plugin for visual studio code so that it pretties the file whenever I save it.  I want to make sure that keeps working.

I have not used lint since my C days. Is this something we run manually or does/can  it happen in vscode?

How would you feel about doing a walk through of all this in the meeting tonight - or the meeting next week? This needs to be a group thing not something we impose on people.

**Comment by kamui-fin** [comment]
> On prettier - with the people I was working with last year agreed on a prettier style - we agreed on single quotes rather than double quotes.

Sounds good, we should use that for this project as well.

> But I prefer the former style, as shorter and more modern, especially when the function declaration is being embedded in another function call. Is there a reason for this style?

I'm not actually sure why it got changed to that. Must be when I accidentally ran `eslint --fix` without a config file. I'll revert that back.

> I have not used lint since my C days. Is this something we run manually or does/can it happen in vscode?

Both, in fact. If you run `npm run lint`, it lists out all warnings, errors, etc. If you have the eslint plugin, it also picks up these errors and highlights it in real time, so that's good to have as well.

>  Also I have the prettier plugin for visual studio code so that it pretties the file whenever I save it. I want to make sure that keeps working.

The prettier config only changes how the file is prettified so it shouldn't impact VSCode's behavior as it should find the config file. 

> How would you feel about doing a walk through of all this in the meeting tonight - or the meeting next week? This needs to be a group thing not something we impose on people.

Sure! I totally agree we should discuss this as a group and come to a style guide we can all work with.

**Comment by kamui-fin** [comment]
>  I'm not sure what restores the button to being active. We have to discuss.

The button component takes in a `disabled` property which can be set to `false` if the button should be active.

**Comment by ddfridley** [comment]
@kamui-fin the files for invitation are ready to check in, but we need to work more on the eslint before checking that in - so it's time to break it into multiple issues and PRs - in hindsight we should have done it this way from the beginning.  It's too many changes for one PR.

- [ ] from main, create a new branch invitation-component#50. checkout the key files from invitation#50 into this branch. make sure it's all working and push it. 
- [ ] After that PR gets merged, create another branch from main for prettier issue #66 and apply the prettier changes.  I think what you have for prettier is fine - but because it impacts every file we need to make it a separate PR
- [ ] After that PR gets merged, create another for ESLint #67. I think we are going to have to work on this one a little more to get the rules right.  Generally I don't want to enforce a style, but do want to check for things that are problems.   And while we are working on this one we will have to keep pulling main and merging it in. 

Does this make sense? 
thx.

**Comment by kamui-fin** [comment]
> from main, create a new branch invitation-component#50. checkout the key files from invitation#50 into this branch. make sure it's all working and push it.

Do I create another pull request for this?

**Comment by ddfridley** [comment]
Yes. I think that's the easiest way.  Ultimately we will dump this pull request.  Unless you san another way to break this into 3?

**Comment by ddfridley** [comment]
I'm closing this PR - the changes were broken into 3 separate PRs and those changes have been made.

**Pull request closed without merging**
