### PR TITLE
Paste google sheets link#55

### PR DESCRIPTION
**Pull request by ice1080**
As mentioned in tonight's meeting, this work isn't 100% completed but it's pretty close so submitting this PR in case there's anything needed to change!
Remaining work on my todo list:
* Fix sample link
* Fix styling of popup so that errors increase size of popup. This is so that shorter and longer errors display fully.
* More testing of various cases
* Look into mocking stuff for storybook so that others can see its usage
  * might have to adjust actual code for handling these types of things?

### CODE REVIEW

**Comment by ddfridley** [comment]
@ice1080 Wow there's a lot going on here. It looks really good.  Do I see just in storybook? 😄 My one comment so far (and I have not tried running it yet) is does the route have to be **google**-auth-callback?  It seems like this part of the functionality would work generically.  Here is the [facebook oauth2 doc]( https://developers.facebook.com/docs/facebook-login/guides/advanced/manual-flow/).  It seems like everything here would work for facebook also.  The state, redirect, etc. I'm not saying we try it - I'm just hoping it becomes a generic interface.  Thoughts?

**Comment by ice1080** [comment]
@ddfridley jest is indeed in storybook, but it doesn't actually run jest tests, it's just used for the storybook interactions. Ironically I was able to get those to work for the upload csv but because of the routes, extra window, and sockets, I don't believe I will be able to get storybook to be fully usable for this component since the app isn't running to pickup the route. I saw how to mock the sockets but not routes.

Regarding the generic auth redirect, I think that might work. The only thing that is currently google specific code is this:
```
let { tokens } = await item.oauth2Client.getToken(req.query.code)
item.oauth2Client.setCredentials(tokens)
```
because the oauth2Client item has both of those methods on it. We can probably check the type of that object and put conditions in for that if you'd like though! Let me know, that's an easy update I can do in this PR.

Current remaining work for this PR (besides that):
* fix sample link
* cancel 2 minute timeout on frontend if already authenticated
* a few more tests, including being signed in to the sockets and that not being signed in blocks socket usage

**Comment by ice1080** [comment]
Alright @ddfridley I believe this is as far as I will be able to take it right now. It should be fully functional and ready for merging. 
Things I did not have time for:
* Stretch goal in #55: "If there was no uniqueId column in the google sheet, add the column and populate it with the uniqueIds generated." - this one opens up several other questions around exactly how this should work so should be done in a different issue
* Stretch goal of: "Only display Paste Google Sheets Component if env has certain variables"
* Stretch goal of: "Figure out storybook mocks of routes maybe?"

**Comment by ddfridley** [comment]
@ice1080 Great work! I created a new issue for the unique id's, for the other 2 points I think we wait and see.  Have a great vacation! Thanks for the contribution.

**Review by ddfridley — APPROVED** [review]
Looks great!

**Pull request merged**
