### PR TITLE
Submission status incongruent#195

### PR DESCRIPTION
**Pull request by ice1080**

### CODE REVIEW

**Comment by ddfridley** [comment]
Looking good.  In the navigation panel:

image

- [ ] can the ovals be the same height as the purple checkmarks?

- [ ] Can the status table be right justified? 

---
I can't tell you how it happened, but after bouncing around between different elections, at one point I got this:

image

After reloading, it went back to normal. Let me know if you can't duplicate.

**Comment by ice1080** [comment]
I haven't been able to reproduce the cut off right side, but after I push the fix for the first two I'm hoping it fixes that since I ditched the old table style.

**Comment by ice1080** [comment]
This one _should_ be good to go with that latest commit. Let me know if you're able to reproduce the issue you mentioned and I can work on that too.

**Review by ddfridley — APPROVED** [review]
I tried and couldn't duplicate the problem with the circles rendering crazy. Look good.

**Pull request merged**
