### PR TITLE
Undebates header bar#22

### LINKED ISSUE #22: Undebates Header Bar
<UndebatesHeaderBar
>

- [x] Magnifying Glass / Search - functionality to be implemented later
- [x] Book/Instructions functionality to be implemented later
- [ ]  Create New takes us to the create undebate page
- [x] User Setting / button have minimal data for now - starting with logout

Here is a link to figma: https://www.figma.com/file/yXrcMvg5EIwdLkHHxIdILh/Undebate?node-id=326%3A5505

image

### PR DESCRIPTION
**Pull request by alex-808**
Closes #22 

@ddfridley I've introduced some new components and things so let me know if you see anything that I should change either aesthetically or logically.

### CODE REVIEW

**Comment by alex-808** [comment]
Kamal updated the Figma with a default user image which I would like to add onto this pull request before it is merged. I'll add it in a new commit.

**Comment by alex-808** [comment]
@ddfridley I've updated the PR so it is ready to review.

One thing I forgot though was the 'Create New' button functionality. You mentioned in the discussion in the issue #22 that there was a way you'd like it implemented but you didn't specify. Is it a redirect similar to the Logout button's redirect to '/sign/out'? That's how I implemented the 'Sign In' and 'Sign Up' buttons for this component. Let me know what needs to change. Thanks

**Comment by ddfridley** [comment]
@alex-808 Looking good!  

- [ ] For the sign/in and sign/up create two separate components - sign-in-button.js and sign-up-button.js and have them return what you are rendering now. If someone clicks on them, navigate to /join.  

But I will create issues to make those buttons do the sign-in and sign-up functionality - using a similar style to the sign out where it expands when you hover over it.

- [ ] For Create New, use the subscribe.js button. There's a new version of that in another PR that will accept a "name" prop, so you can pass in "Create New", and you have to pass in an onDone function.  If onDone is called with {valid: true}, then this component should call electionMethods.createNew() at the moment I don't think you have to pass anything.  It means this component should take electionOM as a prop.  Don't worry if the button says Submit for now.  
- [ ] In your story, pass in a dummy electionOM, with and electionMethods.createNew() that shows something in the story when create new is clicked.  Look at the submit story.
-

**Comment by alex-808** [comment]
Alright @ddfridley, it should be all set.

**Review by ddfridley — APPROVED** [review]
Looks great.  I appreciate that you create stories for the other components you created.  The LinkButton was creative.  I would have done `<button onClick={()=>window.href="/sign/out"}>logout</button>` but working code works!

**Comment by alex-808** [comment]
> Looks great. I appreciate that you create stories for the other components you created. The LinkButton was creative. I would have done `<button onClick={()=>window.href="/sign/out"}>logout</button>` but working code works!

Good to know! I haven't used that window property before. Maybe I'll go back and refactor it at some point. I like it better, it's cleaner.

**Comment by ddfridley** [comment]
Oops. It's supposed to be location.href. and what you have is fine. 

⁣Get BlueMail for Android ​

**Pull request merged**
