### PR TITLE
Undebates list#21

### PR DESCRIPTION
**Pull request by ice1080**
@ddfridley here's the PR for the undebates list per your request; obviously not finished yet.

### CODE REVIEW

**Comment by ddfridley** [comment]
I have pushed an update to get-election-status-methods to this repo. 

When I go to http://localhost:6006/?path=/story/undebates-list--all-moderator-options
and click on the red button to filter on urgent, only 1 of the items shows up, but  2 are marked with the red bar on the left.  Is this working as expected? 

Thanks!

**Review by ddfridley — APPROVED** [review]
It's beautiful!

**Comment by ice1080** [comment]
Hey @ddfridley I still have a few items left on this, and open questions on the issue (and PR discussion). How should I go about doing the rest of the work?

**Comment by ddfridley** [comment]
Oops! I should have asked.  But this looks so great.  Just keep pushing to the same branch, and make another PR when you are ready.

Also, I have one request.  Please use .toLocaleDateString() in the date column to get the date into US format. Kamal, the designer is in India.  I didn't think about it until I started working with it.  I think US users will appreciate it.

**Pull request merged**
