### PR TITLE
feat: add submit component

### LINKED ISSUE #14: Submit Button
```
<Submit
  onDone=()=>{}
>
```
When someone clicks on the Submit button, onDone(true) is called.
figma: https://www.figma.com/file/IQKPx02pkBErpmhQoECoq9/Undebate?node-id=151%3A2529

image

### PR DESCRIPTION
**Pull request by kamui-fin**
Closes #14

### CODE REVIEW

**Comment by ddfridley** [comment]
This is great! I have a few points:

- [ ] when the mouse hovers over the button, the cursor should change into a pointer. See [percent-done-button](https://github.com/EnCiv/unpoll/blob/main/app/components/percent-done-button.jsx) for example
- [ ] In the style, the radius is set to30px. To be really really responsive, figure this out in rem. It might be 1.66 rem or something
- [ ] In the future please avoid '/' in the branch names - it gets confusing when using the git cli in bash.  (I bet you are using the git gui) and please include #14 (this issue number) in the branch name.
- [ ] please include the link to the issue as a comment in near the top of both component and the story - eg
```
// https://github.com/EnCiv/undebate-ssp/issues/14
```
This makes it really easy to refer back the source material and discussion - even after the issue is closed.

- [ ] For extra credit, I have been experimenting with adding a visual onDone indication  in the story - you can see it here: https://github.com/EnCiv/unpoll/blob/main/stories/ask.stories.js -- but I don't think this is too clean and there may be better ways that I haven't found. 

I see I need to add some of these things to the readme so that it will be clear to people in the future. 
Thanks, this is a great start.

**Comment by kamui-fin** [comment]
Sorry, I'm not sure why this was closed. I tried renaming the branch locally and pushing it to github.

**Comment by kamui-fin** [comment]
Apologize for the clutter. I was just experimenting and figuring out how to revert all the renaming and re-open the PR. Will make sure to keep the branch naming conventions in mind for future contributions!

**Comment by ddfridley** [comment]
Looking good. Thanks!

**Pull request merged**
