### PR TITLE
Add Submissions#56 component

### LINKED ISSUE #56: Submissions
```
<Submissions
   className={}
   style={}
   electionOM={[electionObj, electionMethods]}
>

```
See #46 for electionOM details
- [ ] Renders the table of candidates, status, etc
- [ ] See the [discussion in figma](https://www.figma.com/file/yXrcMvg5EIwdLkHHxIdILh?node-id=392:5821#130352071) about possibly combining the two status columns into one
- [ ] The columns can be filtered see the lower figma drawing
- [ ] use the same table component and scrolling component as in #53 
- [ ] The status column is updated elsewhere and each entry is one of ['submitted', 'accepted', 'sent', 'declined'] if there is ever some other word, show the word but no icon. 
- [ ] See the election category component #5 for icons.  Also, is there a way to factor out some common code (not required, may not make sense).

This is highly related to and should share common code with 
- #53 

figma: https://www.figma.com/file/yXrcMvg5EIwdLkHHxIdILh/Undebate-Self-Service-Portal?node-id=390%3A5166

- [ ] See also the screen below that shows how to filter the columns

image

### PR DESCRIPTION
**Pull request by BolunThompson**
Closes #56 

At a past meeting, there was some discussion about where to put miscellaneous functions that operate on electionObj. I put them in `app/components/lib/utilities.js`—should those be moved?

### CODE REVIEW

**Comment by ddfridley** [comment]
@BolunThompson just go with utilities.js for now.  We will figure out how to merge stuff when we have stuff to merge.  Should I go ahead and review/merge this?  Thanks!

**Comment by BolunThompson** [comment]
This should be ready for review then.

**Review by ddfridley — CHANGES_REQUESTED** [review]
Looking great. I like the way you were able to use the candidateTable component. 

- [ ] Make popups disappear when user clicks outside of the popup
If I click on Office at the top of the column, a popup appears that lets me filter based on the office.  If I click on Office again, the popup goes away.  But it took me a while to figure that out.  I expected that the popup would disappear when I clicked outside of it. 

One possibility is useClickAway in https://www.npmjs.com/package/react-use

I have not used this - but it looks interesting

- [ ] Please remove any console lines, as in console.error in app/components/submissions.js

- [ ] Please see the Template in https://github.com/EnCiv/undebate-ssp/blob/main/stories/submission.stories.js and do defaultElectionObj that way. This will make sure it deals with the async update of the electionObj.

- [ ] Please do an Empty story (like in submission) and make sure it works with that.  This is the initial state after a new election is created.  Might want to do that for invite-meter too.

In particular, you will need to handle the case where electionObj.candidates and .timeline does not exist yet, or is empty. But there may be others. 


- [ ] Might as well merge with main

- [ ] Instead of calling it utilites.js can you call it get-candidate-invites-status.js or something like that.  An make the function name match the file name in concept (but not case). 

Thanks!

**Review by ddfridley — APPROVED** [review]
Looking great. Thanks for those changes.

**Pull request merged**
